







spring:



  # 静态资源配置
  resources:
    static-locations: classpath:/templates/

  # thymeleaf 模板框架
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
    encoding: UTF-8



# spring boot 相关配置
  datasource:
    url: jdbc:mysql://localhost:3306/book_manager_system_2019_10_10?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: zz@123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#    # 初始化最大最小
#    initialSize: 5
#    minIdle: 5
#    maxActive: 20
#    # 配置获取连接等待超时的时间
#    maxWait: 60000
#    # 配置间隔多久才进行一次检查，检查需要关闭的空闲连接, 单位是毫秒
#    timeBetweenEvictionRunsMillis: 60000
#    # 配置一个连接在池中的最小生存时间，单位是毫秒
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: SELECT 1 FROM DUAL
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    # 打开 PSCache, 并且指定每个连接上 PSCache 的大小
#    poolPreparedStatements: true
#    maxPoolPreparedStatementPerConnectionSize: 20
#    # 配置监控统计拦截的 filters ，去掉后监控界面 sql 将无法统计, 'wall' 用于防火墙
#    filters: stat,wall,log4j
#    # 通过 connectionProperties 属性来打开 mergeSql 功能: 慢 SQL 记录
#    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000



mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml




